name: onebillioncheckboxes

services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 3s
      retries: 3

  redis-1:
    image: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - redis-1-data:/data
      - ./redis/node-1/redis.conf:/etc/redis/redis.conf
    ports:
      - 6371:6379
      - 16371:16379
    networks:
      redis_network:
        ipv4_address: 172.28.0.101
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 3s
      retries: 3

  redis-2:
    image: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - redis-2-data:/data
      - ./redis/node-2/redis.conf:/etc/redis/redis.conf
    ports:
      - 6372:6379
      - 16372:16379
    networks:
      redis_network:
        ipv4_address: 172.28.0.102
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 3s
      retries: 3

  redis-3:
    image: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - redis-3-data:/data
      - ./redis/node-3/redis.conf:/etc/redis/redis.conf
    ports:
      - 6373:6379
      - 16373:16379
    networks:
      redis_network:
        ipv4_address: 172.28.0.103
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 3s
      retries: 3

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 5540:5540
    networks:
      redis_network:

  app:
    build:
      context: ./
      dockerfile: ./dockerfile
    restart: always
    ports:
      - 3000:80
    env_file:
      - $ENV_FILE_PATH
    depends_on:
      redis-1:
        condition: service_healthy
      redis-2:
        condition: service_healthy
      redis-3:
        condition: service_healthy
    networks:
      redis_network:

networks:
  redis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  redis-1-data:
  redis-2-data:
  redis-3-data:
