name: onebillioncheckboxes

services:
  migrate:
    image: golang:alpine
    environment:
      - REDIS_ADDRESSES=172.28.0.101:6379,172.28.0.102:6379,172.28.0.103:6379
    volumes:
      - ./scripts:/scripts
    command: sh -c "GOOS=linux GOARCH=amd64 go build -ldflags='-w -s' -o /scripts/migrate /scripts && chmod +x /scripts/migrate && /scripts/migrate"
    networks:
      bridge_network:
        ipv4_address: 172.28.0.100

networks:
  bridge_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
